# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            messageformat.js
tagline:          'ICU MessageFormat for Javascript'
description:      'Gender- and plural-capable JavaScript messages using ICU MessageFormat'
url:              http://messageformat.githu.io
baseurl:          /

author:
  name:           'Alex Sexton & Eemeli Aro'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/SlexAxton/messageformat.js
